// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	domain "rings/domain/skywalker/domain"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetMessage provides a mock function with given fields:
func (_m *Service) GetMessage() (*domain.Response, error) {
	ret := _m.Called()

	var r0 *domain.Response
	if rf, ok := ret.Get(0).(func() *domain.Response); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
